# Generated by Django 2.1.5 on 2019-12-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
